Upgrading the fulfillment service to micronaut 4.3.4
oracle-quickstart/oci-micronaut pull request #77
Opened 2024-03-28 18:15 UTC by ChaimaaeROUAI

2024-04-03 08:02 UTC, alvarosanchez requested changes

2024-04-03 08:02 UTC, alvarosanchez commented on .github/workflows/java-ci.yml
> +      - name: Start NATS server
Can we use Test Resources instead of manually creating containers here?

2024-04-15 09:38 UTC, alvarosanchez approved these changes

2024-04-15 10:57 UTC, OthmanMilahOracle approved these changes

2024-04-17 14:06 UTC, Julia3072 approved these changes

2024-04-17 14:48 UTC, merged