Cart to micronaut 4.3.4
oracle-quickstart/oci-micronaut pull request #80
Opened 2024-05-09 13:47 UTC by ChaimaaeROUAI

2024-05-13 13:46 UTC, alvarosanchez requested changes

2024-05-13 13:46 UTC, alvarosanchez commented on src/carts/aws/src/test/resources/application-test.yml
> +#   uri: mongodb://${MONGO_USER:root}:${MONGO_PASS}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/?authSource=admin
Better remove this

2024-05-13 13:46 UTC, alvarosanchez commented on src/carts/lib/src/main/java/mushop/carts/entities/Cart.java
> +public class Cart {
Please convert this to a record

2024-05-13 13:46 UTC, alvarosanchez commented on src/carts/lib/src/main/java/mushop/carts/entities/Item.java
> +public class Item {
Please convert this to a record

2024-05-17 11:53 UTC, alvarosanchez approved these changes

2024-05-17 11:59 UTC, alvarosanchez approved these changes

2024-05-23 09:37 UTC, Julia3072 approved these changes

2024-05-23 09:37 UTC, merged